### ISSUE TITLE
bug: User can join the team twice

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1130]
### Type of feature

🍕 Feature

### Current behavior

<img width="1440" alt="Screen Shot 2023-04-28 at 1 35 46 PM" src="https://user-images.githubusercontent.com/5713670/235303318-0ed4d43a-1288-4923-a4e1-90db93544f63.png">

### Suggested solution

1. We should have some validation for this. 
2. We need to be able to remove users. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
2. In the roles dropdown menu, there is an option to delete a member.
1. There are validations for this but what's weird is that my email is `undefined`. That's why I was able to add myself twice.

| frontend | backend |
| ------ | ------ |
| ![insight-member-2](https://user-images.githubusercontent.com/79809121/235309719-f707707b-41cb-4196-a569-ba02e3010be1.png) | ![insight-member-3](https://user-images.githubusercontent.com/79809121/235309728-c60fbae9-ba10-46c7-8f3e-21ef0989f8cd.png) |

![insight-member-1](https://user-images.githubusercontent.com/79809121/235309734-2cc0a251-f5d1-48f1-a4e0-3fa3065d7aa3.png)

**Comment by OgDev-01** [comment]
Aside adding the owner twice, have we tested adding other team members twice? @bdougie

**Comment by bdougie** [comment]
Confirmed you cannot add another team-member twice. Adding the own twice will always be possible since I have have multiple emails associated to my one github account. 

Perhaps in the future we can de-dup users this way by adding all known emails to the user profile. Maybe a separate field on the user table for "other emails" @brandonroberts?

**Comment by brandonroberts** [comment]
Yes, that's a reasonable approach. We may need some additional checks also to prevent multiple people from claiming the same email but that could be a separate issue.

**Comment by bdougie** [comment]
> Yes, that's a reasonable approach. We may need some additional checks also to prevent multiple people from claiming the same email but that could be a separate issue.

We can display this as a full page error stating someone has already claimed this email.

![image](https://github.com/open-sauced/insights/assets/5713670/cff8fec7-3667-410c-afc7-854dc8ea5644)![Uploading 254457565...]

**Comment by isabensusan** [comment]
Closing this issue since we've moved on from member permissions on individual insight pages, and are now doing team member management at the workspace level. This issue also seems to have been fixed already on workspaces team management by triggering a toast that says "Member has already been added"
