### ISSUE TITLE
Feature: Delete profile

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#1308]
### Type of feature

🍕 Feature

### Current behavior

There is no method showing a way to delete your profile or remove your user. 

I faced this when I was trying to reproduce: https://github.com/open-sauced/insights/issues/1296

### Suggested solution

Add a delete option in the settings. 

https://insights.opensauced.pizza/user/a0m0rajab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by babblebey** [comment]
I second this @a0m0rajab

I indeed craved this feature in 'development', I needed it because I wanted to test out the onboarding experience again. 

I deleted the OAuth app from my GitHub, but obviously wasn't enough, because my user data already existed on the DB, so onboarding over again wasn't possible, unless this data gets deleted.

This one is for sure gonna need `api update`

**Comment by Tejasvp25** [comment]
I'd like to work on this, though I think this issue should be moved to https://github.com/open-sauced/api

**Comment by brandonroberts** [comment]
Hold off on work on this one at the moment. Will provide an update when necessary

**Comment by bdougie** [comment]
This will be completed in #1990
