### ISSUE TITLE
Bug: can't update user profile bio passed 256 chars

### ISSUE THREAD

**Issue by NsdHSO** [open-sauced/app#1446]
### Describe the bug

We don't see a concise error message about why we can't update the bio profile.

As a UI/UX I want to see something like that:
![image](https://github.com/open-sauced/insights/assets/37635083/c32b01d7-eb77-4186-bb5e-8d8a8dadf7cf)

Right now I see only this info
![Screenshot 2023-07-29 at 09 07 59](https://github.com/open-sauced/insights/assets/37635083/02d2200e-77ff-4921-b5b2-4a48c64493bd)

### Steps to reproduce

1. Go to user settings
2. Put 256 char in textarea 
3. Click on the Update Profile

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by aryanas159** [comment]
.take

**Comment by a0m0rajab** [comment]
This is a duplicate of: https://github.com/open-sauced/insights/issues/1309

**Comment by bdougie** [comment]
@a0m0rajab I don't quite follow how this is a duplicate, can you provide more context?

re: this 256 char limit. 

I am not seeing a limit in the API, but only took a quick look https://github.com/open-sauced/api/blob/a4a020f982c669c74a7703dcc1072a897f4413e1/src/user/dtos/update-user.dto.ts#L22

Perhaps we can add a limit indicator similar to how we do in highlights. 

<img width="610" alt="Screen Shot 2023-07-31 at 10 41 59 PM" src="https://github.com/open-sauced/insights/assets/5713670/225ee51b-387a-44ba-8917-24ff116a080e">

**Comment by a0m0rajab** [comment]
@bdougie the one opened the profile is not allowing any updates right now, changing anything in it gives the same error though. 
That's why it's a duplicate.

**Comment by takanome-dev** [comment]
> @bdougie the one opened the profile is not allowing any updates right now, changing anything in it gives the same error though. That's why it's a duplicate.

I think this issue is more about the bio char limit than updating interests. And it's weird that I don't get cors issue when updating my interests. Let's ask the triage team to try it out in #1309

**Comment by NsdHSO** [comment]
> @bdougie the one opened the profile is not allowing any updates right now, changing anything in it gives the same error though. That's why it's a duplicate.

But we can update the profile

**Comment by a0m0rajab** [comment]
Is it only on me not allowing me to update profile? 🤔

**Comment by NsdHSO** [comment]
hmm, I don't know look at this screenshot 
![image](https://github.com/open-sauced/insights/assets/37635083/97defe5d-9f21-4c71-b368-ed30d3ff8d23)

**Comment by jpmcb** [comment]
@a0m0rajab - this is not a duplicate of #1309 since this issue is not replicating the cross site origin problem you ran into. I'm able to update my bio just fine.

![Screenshot 2023-08-02 at 9 52 29 AM](https://github.com/open-sauced/insights/assets/23109390/8ef59f8e-4b0c-46f7-a34f-1cc56e132b26)

Let's continue the conversation on CORS problems in that issue and not here.

--- 

On the character limit, I do believe there is an API limit since the varchar limit is set to 255:

https://github.com/open-sauced/api/blob/028699dc2bcff7a187d5f9dc609f1803a541c893/migrations/20220510165555_add_users.sql#L33

This would require API changes to increase the length. But 255 is probably fine for most people since most bio's are rather limited across the internet anyways. For example, here's my Twitter/X bio:

![Screenshot 2023-08-02 at 9 57 15 AM](https://github.com/open-sauced/insights/assets/23109390/e5419617-be13-4df3-8037-1f6a27a8de13)

Also notice the character indicator. As Brian said, the solution here is to add a `x/255` indicator to the bio field.

**Comment by takanome-dev** [comment]
cc @aryanas159 Just checking in - do you need any help with this (or have questions)?

**Comment by aryanas159** [comment]
> cc @aryanas159 Just checking in - do you need any help with this (or have questions)?

Sorry @takanome-dev , I forgot that I assigned myself to this issue, I'll look into it.

**Comment by takanome-dev** [comment]
> I forgot that I assigned myself to this issue, I'll look into it.

No worries, it's not high priority 

<img src="https://media0.giphy.com/media/IfFN6NwhaUl3CI4mgG/giphy.gif"/>
