### ISSUE TITLE
Bug: we cant see the sidebars on small screens 

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#1510]
### Describe the bug

If we go to small or medium screens, there is no way to see the side bars: 

![image](https://github.com/open-sauced/insights/assets/18273833/9f34023b-b634-4b2f-8d37-264e421c43c1)

### Steps to reproduce

1. go to feed 
2. make the screen small or medium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by babblebey** [comment]
The Sidebar had intentionally been hidden for Responsiveness purposes, and it was further worked on with the PR #1490

Are you suggesting that we should still look for a way to factor it into display on mobile!?

I could be all in for this idea too, but this is if we're looking to factor in display for the `HighlightFilter` component, because it's the only component looking like it's imperative.

We could look to implement a Side Navigation to hold this and show it onClick a trigger..

Though the Right sidebar is non-imperative IMHO and we needn't cluster the very small mobile viewport with an extra option but maybe everything can fit into the Side Navigate from top of bottom, that way we are still able to keep the `Newsletter` component too (it may look imperative).

**Comment by Deadreyo** [comment]
@bdougie @brandonroberts 
any updates on the status of this issue? Is it ready to be taken on?
also is there a design available for this, or shall I suggest a design?

My suggestion would be to add this part to the mobile view: 
![image](https://github.com/open-sauced/app/assets/52013393/a3a10bbd-101f-4f83-9e63-814406903038)
as well as the Repositories filter, before the highlights list

**Comment by bdougie** [comment]
There is no design but fine to see your interpretation. Radix and Headless UI not have an options.

The List feature also has a drawers designed for filtering.

cc @open-sauced/design

**Comment by Deadreyo** [comment]
.take

**Comment by Deadreyo** [comment]
currently the repo list is shown like this:
![msedge_bn3r00L9g3](https://github.com/open-sauced/app/assets/52013393/c2279eb7-8446-4cf2-a377-f59e701114d2)

For small screens, this takes too much space and so it will be like this for them: 
![msedge_RThMYvFlcD](https://github.com/open-sauced/app/assets/52013393/2577fe3f-00a4-43a5-86b6-d17ecea7d50b)

How about making this the default for all screen sizes? It looks much better like this IMHO @bdougie

**Comment by brandonroberts** [comment]
Will revisit when we refresh the feed page
