### ISSUE TITLE
Bug: odd behavior when select filters

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#1512]
### Describe the bug

If you go to highlight page, and select filters, you can see a resize of the feed there: 
https://github.com/open-sauced/insights/assets/18273833/8b2f8adf-7814-48d3-b53c-c9ceb4f2edb7

### Steps to reproduce

1. go to : https://insights.opensauced.pizza/feed
2. open debugger mode and set screen to nest hub max (I faced it on normal screen as well) 
3. choose filters and change them. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by RitaDee** [comment]
Hello @a0m0rajab and @brandonroberts,

I wanted to bring to your attention PR https://github.com/open-sauced/insights/pull/1553. This PR has successfully addressed the mentioned issue.

**Comment by RitaDee** [comment]
@a0m0rajab and @brandonroberts, IMHO I think this PR https://github.com/open-sauced/insights/pull/1553 has fixed this Issue. What do you think?

**Comment by ThePiyushAggarwal** [comment]
Hi! @a0m0rajab 

I looked into this issue. I know why this happens but not sure about what the right solution is.

This happens because of the text inside the posts. If the text contains a large word, it tries to take up more space. When you changed filters, some of the posts in those filtered data must have long words or links.

[highlights-posts-issue.webm](https://github.com/open-sauced/app/assets/27003616/865ed51f-6ee7-4995-a52f-aed1e2594425)

Possible solutions
- Giving a maximum length to the display name of the link. An ellipse at the end.
- Giving a fixed width to the post. Don't know about this one.

**Comment by RitaDee** [comment]
Hello @a0m0rajab,

Could you verify if the reported issue persists, as indicated in the provided link: https://insights.opensauced.pizza/feed?

I'm unable to replicate the issue on my end. Thank you.

**Comment by takanome-dev** [comment]
This has been fixed but I couldn't find the pr though :sweat_smile:
