### ISSUE TITLE
Bug: error when submitting collaboration

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#1632]
### Describe the bug

When I try to send a collaboration message to [Nick Taylor](https://insights.opensauced.pizza/user/nickytonline/), I get a 401.

![image](https://github.com/open-sauced/app/assets/34313413/938b1903-1bc9-4769-bc18-8d305655d184)

### Steps to reproduce

1. Go to [Nick Taylor](https://insights.opensauced.pizza/user/nickytonline/)
2. Click the collaborate option
3. See the error

### Browsers

Chrome

### Additional context (Is this in dev or production?)

production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by babblebey** [comment]
Hey @BekahHW is this a different experience from #1634??

**Comment by BekahHW** [comment]
@babblebey no. Even when fulfilling the minumum, I get this error when I try to collaborate.

**Comment by babblebey** [comment]
Very well @BekahHW, after some testing I think the issue is from the endpoint itself, nothing peculiar to the client-side, this is because I have also tested the endpoint ([User Collaboration Servie](https://beta.api.opensauced.pizza/#/User%20Collaborations%20service/addUserCollaboration)) via swaggerUI, same 401

![image](https://github.com/open-sauced/app/assets/25631971/a3e007ce-e2d3-4ca6-a40a-7baf02d9b020)

Though I saw it required authorization, i.e. a `sessionToken` from client present when a user is logged in, but in the presence of that, the 401 error persists... this error code isn't specifically documented, so I cannot deduce exactly what it means different from being `Unauthorized`.

I'd like @jpmcb and @OgDev-01 to take a look at this.

**Comment by babblebey** [comment]
I've uncovered in the issue for this created in the API repo, that user who are not paid users i.e. are not subscribed to the upgraded insights, will not be able to use the collaboration request feature. 

Hence the `401 Unauthorized` error, the feature is only available for paid user.

So, the client-side response is just correct, and the 401 error is the thing that needs to be handles properly.

We can have a check triggers the `toast` (if error is 401) with a message stating that the Collab request feature is for only paid user and encourage them to subscribe too.

**Comment by OgDev-01** [comment]
> We can have a check triggers the toast (if error is 401) with a message stating that the Collab request feature is for only paid user and encourage them to subscribe too.

Would you mind adding this quick feedback in a PR?😊... cc: @babblebey

**Comment by babblebey** [comment]
Sure, I'm already working on an Issue that relates to this.

So, I'll .take it
