### ISSUE TITLE
Feature: Improve UX for non-connected accounts

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1675]
### Type of feature

🍕 Feature

### Current behavior

N/A

### Suggested solution

<img width="1305" alt="image" src="https://github.com/open-sauced/app/assets/27322879/46d1e9ab-6b5d-4024-a182-84e868416a75">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Instead of "is this you," we can leverage the "invite to opensauced" user flow that @diivi put together. If a user is not logged in, they would be forced to login before connecting. We can also track referrals to encourage individuals to invite more folks to OpenSauced, to get either collaboration credits or a free month of the paid tier. 

https://viral-loops.com/blog/dropbox-grew-3900-simple-referral-program/
https://github.com/open-sauced/engineering/issues/57

## invite to opensauced button

This could be invite instead of connect. 

![Screen Shot 2023-09-05 at 11 54 07 AM](https://github.com/open-sauced/app/assets/5713670/8e84537a-af80-4c8a-8103-0c74d5e9103d)

## user flow
If a user has connected their email publicly on github or social accounts. We share a direct link connect with then and share context.

## email
![Screen Shot 2023-09-05 at 11 56 39 AM](https://github.com/open-sauced/app/assets/5713670/67592e21-7a0b-4cb7-94a4-9fcb4b120c30)

## X
![Screen Shot 2023-09-05 at 11 56 39 AM](https://github.com/open-sauced/app/assets/5713670/325ec056-c602-4a18-9cac-dc79daadca89)

**Comment by isabensusan** [comment]
Hey! Sory I left this on the backburner for a bit. Here's a reviewed design taking into account @diivi 's existing user flow.

### [Figma file](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=11118-34666&mode=design&t=gJAdGuJZeiVI1Rih-4)

<img width="1341" alt="image" src="https://github.com/open-sauced/app/assets/27322879/7803204f-4c6f-4d2c-ac11-953f64272983">



### See the full flow in [figma](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=11118-34666&mode=design&t=gJAdGuJZeiVI1Rih-4) 
<img width="1426" alt="image" src="https://github.com/open-sauced/app/assets/27322879/37270965-0d55-4116-9ebe-d4337f9a157f">

**Comment by isabensusan** [comment]
A separate comment is that we need to figure out our auth flow better so we can make flows like these make more sense. We can work with what we have right now, but I'll make sure to add this task to our design roadmap

**Comment by bdougie** [comment]
[MathiasExorde](https://insights.opensauced.pizza/user/MathiasExorde) is the top contributor on github based on commits (probably a cron). 

His profile on OpenSauced shows nothing since we do not index - https://github.com/exorde-labs/TestnetProtocol

This is confusing when users look at their account. Noticed the same for [Peterp](https://insights.opensauced.pizza/user/peterp)

I'd love to prioritize this next. Show a note on non-connected accounts that data will be limited until they connect their account or index repos via insight pages.
