### ISSUE TITLE
Bug: Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [open-sauced/app#1681]
### Describe the bug

The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this.

Screenshot
<img width="960" alt="Screenshot 2023-09-07 192207" src="https://github.com/open-sauced/app/assets/91591901/2545146a-d86f-436e-9335-fb43f5e29d28">

Additional Context
Won't change anything in the code as such would replace the twitter-logo with a new file. No code will be touched.

@bdougie , @isabensusan 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

### Steps to reproduce

Scroll to footer section and see twitter old logo

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
There are other places we are using the Twitter bird.

- Highlight Cards

It looks like ReactIcons has updated the logo to be `XTwitter` instead of `Twitter`

https://react-icons.github.io/react-icons/search?q=twitter

This should be a straight forward fix. 

## Assigning

Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by lalitkumawat1m** [comment]
.take

**Comment by lalitkumawat1m** [comment]
<img width="768" alt="Screenshot 2023-09-08 031403" src="https://github.com/open-sauced/app/assets/91591901/a3ba7577-749b-47b5-909c-4d6a55a27d9e">

x icon is available on the react icons website but in the code, it is giving an error, 
'"react-icons/fa"' has no exported member named 'FaXTwitter'. Did you mean 'FaTwitter'?

**Comment by lalitkumawat1m** [comment]
Hey @bdougie,
I have created a pr regarding this issue could you please review it and give feedback to me?
