### ISSUE TITLE
Feature: Add contributors page for a list

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#1710]
### Type of feature

🍕 Feature

### Current behavior

When a user opens a list and clicks on the contributors tab, we want to display a paginated list of the contributors

![image](https://github.com/open-sauced/app/assets/42211/a2673c5c-5380-41fc-a4e5-10195d1e62fd)

### Suggested solution

- From the `/hub/lists` page, select an item from the list
- Click on the `Contributors` tab. The URL is `/lists/{listId}/contributors`
- The contributors table is displayed for the contributors added to that particular list

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
The endpoint for fetching the contributors for a list is https://beta.api.opensauced.pizza/#/User%20Lists%20service/getUserListContributors

**Comment by brandonroberts** [comment]
The Lists hub can be accessed at `/hub/lists`. It currently redirects to `/hub/insights` while in development

**Comment by brandonroberts** [comment]
We have a table component already available here 

https://github.com/open-sauced/app/blob/beta/components/organisms/ContributorsTable/contributors-table.tsx

**Comment by brandonroberts** [comment]
The page route is stubbed out at https://github.com/open-sauced/app/blob/beta/pages/lists/%5BlistId%5D/contributors.tsx

**Comment by nickytonline** [comment]
@brandonroberts, for the table component (https://github.com/open-sauced/app/blob/bf14435b632bda85739342f6afb8fa168aedec1a/components/organisms/ContributorsTable/contributors-table.tsx) it displays different information then the screen shot, as it contains a predefined grid row component.

```jsx
          <ContributorListTableRow
            topic={topic}
            contributor={contributor}
            key={i}
            selected={!!selectedContributors?.find((selected) => selected.user_id === contributor.user_id)}
            handleOnSelectContributor={handleSelectContributors}
          />
```

![CleanShot 2023-09-22 at 10 17 51](https://github.com/open-sauced/app/assets/833231/e2d3a65f-8c8c-453d-bc65-44cd1fc26602)

Should I be implementing a contributor table row for this work?

Also, when retrieving the list information (not contributors endpoint), i.e. `lists/${listId}`, it does not include the user who created the list.

Here is a sample output:

```json
{
  "id": "dfb776fc-31be-44a0-8ae0-332fbb89a643",
  "name": "The Best Contributor List",
  "is_public": false,
  "created_at": "2023-09-21T17:16:43.387Z",
  "updated_at": "2023-09-21T17:16:43.387Z",
  "deleted_at": null
}
```

I imagine I could get the current user's list (if they have any) and do it that way, but that seems like a lot of unnecessary work.

I bring it up because of this existing check for the owner.

```javascript
const isOwner = !!(userId && list && `${userId}` === `${list.user.id}`);
```

We also don't have the number of contributors in the list. I have this information when I get the contributors list, but the layout has no knowledge of this call as it's done in the page component. I've got some workarounds, but TLDR; just wondering if the payload returned from the lists endpoint needs to be enhanced.

**Comment by nickytonline** [comment]
Ahh, nvm for the table component. I found the pagination and header controls in another page. That'll probably sort it out.
