### ISSUE TITLE
Bug: Highlights "Repositories" table rerenders with duplicates and spills over page eventually

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1779]
### Describe the bug

Noticed this while investigating: https://github.com/open-sauced/app/issues/1778

https://github.com/open-sauced/app/assets/23109390/8c486770-0c8e-4fe2-9034-fde0bada0b48

Watch the right side as I quickly flip between the "Home" and "Following" tabs: the "Repositories" field grows and grows, eventually spilling over the bottom of the page and containing many of the same repo, over and over again.

A few suggestions:
- Duplicate repos do not make sense
- We should have some sane limit, maybe 15 at most? Open to suggestions
- This table should not spill over the bottom of the page
- Rerendering this each time the user flips from the "Home" tab to the "Following" tab (and back again) probably also doesn't make sense. A static rendered table of repositories would be the most smooth user experience.

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/feed
2. Flip many times from "Home" to "Following" (and back again)
3. Notice the "Repositories" table on the right is rerendered many times and eventually spills over the page containing duplicates.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 5hraddha** [comment]
As this issue is still marked as Triage, thought it would be great to discuss before taking it up. After looking into this bug for a while, found the reason for "Repositories" field growing and eventually, spilling out. As of now, the code has **a limit of 10 repos** to be listed in the list but while the list is getting rendered, the value for the`key` props of the list items gets duplicated and thus, the React is not able to re-paint the UI properly.

Example:
For "Home" tab, I've the following list of repos to be rendered:
<img width="819" alt="image" src="https://github.com/open-sauced/app/assets/27571141/4bb676c9-0d07-4b47-a686-c0ed3a5ccc7a">
 The code that runs to render the list of repos is:
```js
// components/molecules/HighlightsFeedCard/highlights-filter-card.tsx
        {repos.map(({ repoName, repoIcon, full_name }) => (
          <div
            onClick={() => handleClick(full_name)}
            key={(repoName + repoIcon) as string}
            className={`${
              selectedFilter === full_name ? "border-orange-600 bg-orange-200" : ""
            } flex hover:border-orange-600 hover:bg-orange-200 cursor-pointer gap-1 w-max  p-1 pr-2 border-[1px] border-light-slate-6 rounded-lg text-light-slate-12`}
          >
...
          </div>
        ))}
```
As you can see the code snippet above has `key={(repoName + repoIcon) as string}`. This works fine as long as we have unique value for the combination but creates issue when we get a duplicate value for the combination. 

Now, for "Following" tab, I've the following list of repos to be rendered (duplicate values for the `key` combination):
<img width="990" alt="image" src="https://github.com/open-sauced/app/assets/27571141/0fdd6d2d-7383-4d50-b4bf-54002a52def0">
Since, now we've duplicate values for `key={(repoName + repoIcon) as string}`, it creates a problem. 

**Possible Solution**
Update `key={(full_name + repoIcon) as string}` probably as `full_name` of repo is still unique.

**Comment by takanome-dev** [comment]
@5hraddha if the proposed solution can fix this issue, feel free to open a pr.

**Comment by nickytonline** [comment]
@5hraddha, using `full_name` for the `key` sounds good.

**Comment by 5hraddha** [comment]
Thank you @nickytonline !  I've few quick clarifications to make sure I'm taking the suggestions by @jpmcb in account:
- **Duplicate repos do not make sense**
We do have instances where while fetching the list of repositories, the code is feching two different URLs of the same repo like - `open-sauced/insights` and `open-sauced/insights/issues/1543`. So, on the UI, we have two icons for the same repo. I'll mark such cases as duplicate and keep one instance alone. Will that be okay?

- **We should have some sane limit, maybe 15 at most?**
Since the code already has a limit of 10, I believe this is taken care of.

- **This table should not spill over the bottom of the page**
This will be taken care by fixing the duplicate key props issue.

- **A static rendered table of repositories would be the most smooth user experience**.
On the "Home" tab, the code fetches list of repos in User Highlights and on the "Featured" tab, it fetches repos as part of Featured Highlights. (Sorry, I'm not sure how are they different) These fetch requests are made fresh every time the user clicks on one of the tabs. How do you want to handle this? Any ideas? Do you just want fetch both the list of repos once in `getServerSideProps`, so that  Next.js could pre-render it and not look for any updates later.
