### ISSUE TITLE
Bug: No indication of a limit for insight pages

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1785]
### Describe the bug

![Screen Shot 2023-10-02 at 3 10 06 PM](https://github.com/open-sauced/app/assets/5713670/3b715b5b-fb5c-4ee1-bb00-0182ff8d647a)

While preparing for a stripe demo, I needed to add 50+ repos to one insight page. Note that the button is disable, but no message is displayed. 

![Screen Shot 2023-10-02 at 3 10 06 PM](https://github.com/open-sauced/app/assets/5713670/9fc00fd9-5a0b-452f-b5d2-f521e8b4d55d)

### Steps to reproduce
Add 50+ repos from https://github.com/stripe-samples/ to one insight page. 

The limit appears to be 49.

https://insights.opensauced.pizza/pages/bdougie/23/repositories

https://insights.opensauced.pizza/pages/bdougie/23/dashboard

_We should add a feature add all repos from an org or a CSV_

### Additional context (Is this in dev or production?)

A tool tip on hover of the button would be enough. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
> The limit appears to be 49.

That _feels_ rather low (especially for some orgs that have 100s of repos that may have many different teams associated with any number of them. Just look at AWS's open source org: over 700 https://github.com/orgs/awslabs/repositories?type=all)

Maybe a separate issue, but would be cool to see this limited expanded for super user orgs out there.

**Comment by bdougie** [comment]
> Maybe a separate issue, but would be cool to see this limited expanded for super user orgs out there.

True. We need someone to hit the limit first. At the moment most insight pages are 2 repos on average. I am sure if we allowed org indexing it would be hire. No is going to manually add them today. We can for sure adjust the limit based on super user.

**Comment by takanome-dev** [comment]
That's weird because I was able to add 50+ repos -> https://insights.opensauced.pizza/pages/takanome-dev/697/repositories

![2023-10-03_09-08](https://github.com/open-sauced/app/assets/79809121/fcd934a5-e5b2-40b7-ad1e-9665a971ccae)

When I added the 10th repo, the button was disable (I saw that the limit is 10 in the code) but for some reason it starts working again and I added 54 repos so far. Humm 🤔
https://github.com/open-sauced/app/blob/f43502655626f6e588caca352e6340a7fcfb2560/lib/store/index.ts#L8
https://github.com/open-sauced/app/blob/f43502655626f6e588caca352e6340a7fcfb2560/components/organisms/InsightPage/InsightPage.tsx#L470-L480
