### ISSUE TITLE
Feature: Helper tooltips for dashboards

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1806]
### Type of feature

🍕 Feature

### Current behavior

I've gotten feedback from users (even maintainers) that open up our dashboards but aren't sure what they are seeing and why it is helpful.

### Suggested solution

I think a small step forward towards educating users could be adding some context through tooltips that display when the user hovers over a KPI title. 

The copy on this mock is not great, but it's a way of showing what can be done:

<img width="799" alt="image" src="https://github.com/open-sauced/app/assets/27322879/c17a479d-89c3-46dc-b8a0-fb366a7d01f5">

We can continue to tackle this issue by creating our own documentation for OSS metrics and how to measure a project / use our platform, and linking that content in the helper tooltips. That way if a user asks themselves "why is this useful?" they can just hover over the title and get more info on it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
@isabensusan. I'd love to get @OgDev-01 to work on this. Let me know if there is anything blocking this other than copy. 

@OgDev-01 work with @BekahHW for copy.

**Comment by OgDev-01** [comment]
Hey @BekahHW, here are the list of labels that needs copy from the dashboard

- Contributors
- Spam
- Merged Prs
- Unlabeled

The area of usage 
![image](https://github.com/open-sauced/app/assets/62995161/98826f86-002f-451e-aa38-df6b1b591541)

**Comment by BekahHW** [comment]
@isabensusan in the example, you have a section for "Why is this important? **Read more.**" is that something you want copy for as well?

**Comment by isabensusan** [comment]
@BekahHW Ideally yes, but if it's going to be a blocker we can just start with the definition of the metric + a link to the full glossary (if necessary) and we can look into adding more context in a second iteration

**Comment by BekahHW** [comment]
## Requested
- Contributors: People who have made pull requests to the selected repositories over the last 30 days.
- Spam: An issue or pull request labeled as spam on the selected repositories over the last 30 days.
- Merged PRs: Pull requests that have been successfully merged into the codebase in the last 30 days.
- Unlabeled PRs: The number of open or closed PRs that have not been labeled in the last 30 days.

## Additional
- PR velocity: the average time to completion from Pull Request.
- Activity: Activity tracks PRs over the last 30 days. High indicates more than 80 PRs. Medium is between 5 and 80 PRs. Low is below 5 PRs.
- Alumni Contributors
- Active Contributors
- New Contributors
- Churned Contributors

It would be useful to have tooltips for the line graph as well. It could be either when you hover over the part of the line or on the heading for the PR overview. I prefer the heading only because the colors could be so close together.

- PR Overview tells the story of the Pull Requests submitted in the last 30 days:   
	- Green line: Open PRs.
	- Red line: Closed PRs.
	- Purple line: Merged PRs.
	- Gray line: Draft PRs.

**Comment by BekahHW** [comment]
@isabensusan let's shoot for a second iteration with the read more unless I can get to it before then.
