### ISSUE TITLE
Bug: `.take` command is not working as expected

### ISSUE THREAD

**Issue by brainconnect93** [open-sauced/app#1945]
### Describe the bug

After going through the contribution guide, I tried assigning a task to myself using the .take command. Here is the error I got.

Screenshot
![issue](https://github.com/open-sauced/app/assets/78634841/9a8b6f2c-2f1c-4265-a2e1-1dc48fc3bbe2)

### Steps to reproduce

1. Go to "https://github.com/open-sauced/app/issues/1937"
2. Use the .take command to assign to self

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
This is related to a feature I implemented yesterday, https://github.com/bdougie/take-action/pull/24.

I have a fix up that @bdougie will most likely merge later today, https://github.com/bdougie/take-action/pull/25

For the app repo, I'm going to go ahead and add the blocking labels so that it will work. This was planned work anyways.

**Comment by bdougie** [comment]
We will probably want to target this to the next release as well. Running the action from main currently https://github.com/open-sauced/app/blob/beta/.github/workflows/triage.yml#L16
