### ISSUE TITLE
Bug: 404 errors in the browser console with the message "You are not following this user"

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#1950]
### Describe the bug

I've been seeing this error pop up multiple times if you go to the feed page. Not sure if it's happening elsewhere.

### Steps to reproduce

1. Go to app.opensauced.pizza/feed
2. Open up the browser dev tools and go to the console tab.
3. Notice the 404 errors.

![CleanShot 2023-10-19 at 09 54 53](https://github.com/open-sauced/app/assets/833231/50e5b1fb-bdd7-4405-9c1b-d5d5405fa7ba)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
I took a look at this and noticed the `useFollowUser` hook in the individual highlight is what causes the many console logs because it tries to check for following on all the highlights author
https://github.com/open-sauced/app/blob/87daa09b67722db0f48d2f44294cf09ac3c45bca/components/molecules/ContributorHighlight/contributor-highlight-card.tsx#L123

The API returns an error if you are not following the author of the highlight. The logs are thrown out there by our global fetcher, which is the expected behavior. But we can optimize the FE implementation to only make that request when the more option menu is opened in a highlight.

### Proposal
Move the dropdown menu content to a seperate function and make the `useFollowUser` call inside it. This way, only the highlight that has the dropdown open will make that call and check if the user follow or not

This is the sole reason why we are making that call 👇👇
https://github.com/open-sauced/app/blob/87daa09b67722db0f48d2f44294cf09ac3c45bca/components/molecules/ContributorHighlight/contributor-highlight-card.tsx#L489-L497
