### ISSUE TITLE
Feature: Add placeholder if user has no connections requests

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#1966]
### Type of feature

🍕 Feature

### Current behavior

There's currently nothing there if you don't have connection requests.

### Suggested solution

Something like this might work and prompt users to connect:

![start collaborating with others](https://github.com/open-sauced/app/assets/34313413/4d310e93-b294-46a0-bd1a-449703da5d95)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Satoshi-Sh** [comment]
I will work on this. .take

**Comment by OgDev-01** [comment]
We currently have a placeholder for this
![image](https://github.com/open-sauced/app/assets/62995161/b04b3067-35ab-4032-ba35-893dcfee1677)

But the issue here is having a blank page when you have no pending requests. i've opened a discussion in https://github.com/open-sauced/engineering/issues/177 for the improvement of this... but in the mean time, i'll add same placeholder for users who have requests but have no pending one
