### ISSUE TITLE
Bug: Blog post highlights make up random repos

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1995]
### Describe the bug

<img width="570" alt="Screen Shot 2023-10-24 at 3 54 11 PM" src="https://github.com/open-sauced/app/assets/5713670/3df5eb7f-f524-49e1-9790-328177dcf1b5">

### Steps to reproduce

The need for recognition is not a repo and every blog highlight should be linked to a repo. 

The solution should enforce a repo being tagged on a blog highlight.    

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
<img width="615" alt="Screen Shot 2023-10-24 at 4 05 54 PM" src="https://github.com/open-sauced/app/assets/5713670/549679ed-8cab-48a6-8d74-a699b2446f80">

The input has a place to tag a repo, not sure why it is not required at the moment.

**Comment by shamimbinnur** [comment]
Although it's triage labeled, can I take it anyway? @bdougie

**Comment by bdougie** [comment]
We still need to triage it. We are trying to build a contributor culture where folks share an idea for the approach before we assign. 

We have had too many issues sit assigned with no response for months. With that said, can you look at the code make a suggestion for an approach?


If you are on the @open-sauced/triage team, you are able to remove the label.

**Comment by shamimbinnur** [comment]
**Why is this happening:**
 
Currently, the repository is being tagged automatically based on the link given by the user.
The logic behind extracting the repo URL from the given link is not handled for the blog post.
That's the reason it is just splitting unwanted text from the blog link and treating it as a repository URL.

[The logic here ](https://github.com/open-sauced/app/blob/bcdecfc69440d8d68e7b19347ccb0e300830195b/components/molecules/HighlightInput/highlight-input-form.tsx#L433C102-L433C102)

**The way it can be fixed:**
1. Implement logic to prevent automatic extraction of the repository URL when it's a blog post.
2. Since no repository is currently tagged, display an alert message prompting the user to tag at least one repository.

@bdougie

**Comment by bdougie** [comment]
Thanks for exploring this @shamimbinnur. Assigned
