### ISSUE TITLE
Bug: Project storybook leading to 404

### ISSUE THREAD

**Issue by babblebey** [open-sauced/app#2017]
### Describe the bug

This URL is from the [Readme](https://github.com/open-sauced/app#-storybook) which should link to the Project storybook at https://design-insights.opensauced.pizza/; The page currently is not found hence loading to a 404 error. 

![image](https://github.com/open-sauced/app/assets/25631971/26967fdb-1e41-42df-9705-5bb29de52c05)

If there's been a change in the subdomain/domain that hosts the project, I suggest it should be updated in the ReadMe or if there hasn't been any change in the url, then this should be addressed.

### Steps to reproduce

1. Go to https://design-insights.opensauced.pizza/

### Browsers

Chrome

### Additional context (Is this in dev or production?)

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Looking at the build logs, the app is being built instead of the Storybook site. I think I know what's up. We recently updated the netlify.toml as it was misconfigured, https://github.com/open-sauced/app/pull/1961.

Previously, the commands were using what was configured in the Netlify UI. Since we're not using a monorepo, the netlify.toml configuration runs the same on both the Storybook and App sites.

For now, we'll need to remove the build command from the netlify.toml.

```diff
[build.environment]
NODE_VERSION = "18"

- [build]
- command = "npm run build"
- publish = ".next"

# more config....
```

To validate this fixes the issue, ensure that the app and Storybook deploy previews both load their respective sites.

**Comment by nickytonline** [comment]
If you're up for it, feel free to take this one @babblebey.
