### ISSUE TITLE
Feature: Replace languages in contributors list with Most Used Languages

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2163]
### Type of feature

🍕 Feature

### Current behavior

When you go to the contributors tab in a list, like [this one](https://app.opensauced.pizza/lists/90109872-8c67-4c26-838b-d12c18df08c4/contributors), you'll see the column for language. 

<img width="1298" alt="Screenshot 2023-11-16 at 11 26 10 AM" src="https://github.com/open-sauced/app/assets/34313413/17921d74-a0d2-4960-b50d-3c2db568f719">

### Suggested solution

A clearer and more useful data point would be Most Used Languages. To make the update, we'll need to:
- Change the Column Name to Most Used Languages.
- Change the calculation to show the top 2 languages. (We're currently calculating the top five in the contributor's profile)
 <img width="379" alt="Screenshot 2023-11-16 at 11 29 42 AM" src="https://github.com/open-sauced/app/assets/34313413/62b1e982-c586-4f92-8242-a87a0651824f">

- Remove the number that's currently being calculated in the column.

<img width="810" alt="Screenshot 2023-11-16 at 11 35 26 AM" src="https://github.com/open-sauced/app/assets/34313413/1ad9ee7b-7b30-47ee-a72b-1e2fc4a786b9">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jdwilkin4** [comment]
Hey @BekahHW ! 

Were you also looking to change the current behavior here where it currently shows no language?

<img width="777" alt="Screenshot 2023-11-17 at 7 12 19 AM" src="https://github.com/open-sauced/app/assets/67210629/0ae5c684-dd0c-4c24-9268-6ce16b8a507a">

When you go to their profile it does show one language?  


<img width="438" alt="Screenshot 2023-11-17 at 7 16 19 AM" src="https://github.com/open-sauced/app/assets/67210629/75d60ca4-107e-46ae-a191-b7544eabfee5">

Maybe we could just show that instead of the dash?

**Comment by BekahHW** [comment]
@jdwilkin4, that's a good call. Show the one language.

**Comment by jdwilkin4** [comment]
Sounds good. 👍 

Is this available for contribution or does it still need triage?

**Comment by jdwilkin4** [comment]
.take
