### ISSUE TITLE
Bug: Navbar moves when clicking "Select a Filter" in the Insight Page's Reports tab

### ISSUE THREAD

**Issue by adiati98** [open-sauced/app#2166]
### Describe the bug

When I clicked the "Select a Filter" menu, the navbar moved. And it moves everytime the menu is clicked.

## Screen Recording

![navbar moving](https://github.com/open-sauced/app/assets/45172775/d749cc88-080e-40f0-981b-9cab77dc86a3)

### Steps to reproduce

1. Go to an "Insight" page.
2. Click "Reports" tab.
3. Click the "Select a Filter" menu.
4. Pay attention to the navbar.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Satoshi-Sh** [comment]
I tried to fix this but couldn't. I will share what I found so far.

When the select window opens, the y-scrollbar disappears(users cannot scroll the page).  That's why the nav bar takes more width for the disappeared scroll bar.
  
![Screenshot from 2023-12-03 14-11-25](https://github.com/open-sauced/app/assets/73622805/d9c8e4a8-d20a-4b97-ab92-7ce70c435fe8)

**Comment by brandonroberts** [comment]
Closed with current removal of reports
