### ISSUE TITLE
Bug: filter not showing the correct number on explore page.

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2290]
### Describe the bug

You can see from the image below, it should be showing 10/page, but if you look next to repositories, it shows you that it's displaying 50. 

![image](https://github.com/open-sauced/app/assets/34313413/c4a09679-095e-467c-8645-4c6b50ccc90d)

### Steps to reproduce

Go to the explore page. 

You can check it out [here](https://app.opensauced.pizza/ai/dashboard/filter/most-active?range=30)

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by aryanas159** [comment]
This is caused because initially, the value of the "limit" query is undefined and the API, by default, provides 50 results when limits are undefined. Still, the dropdown shows the first option as no values are mapped to undefined. 
There are many ways we can fix this, one way is to change the default value of the dropdown in case the limit is undefined.

Should I make a pull request as it currently needs triage?

**Comment by nickytonline** [comment]
@OgDev-01, does #2227 résolve this issue as well?

**Comment by OgDev-01** [comment]
> @OgDev-01, does #2227 résolve this issue as well?

Yes, this is fixed there
