### ISSUE TITLE
Bug: highlight allows you to submit when over the character limit

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2450]
### Describe the bug

To have a highlight post successfully, you need to stay within the character limit. However, right now, our protections to disable posting aren't capturing that limit of 500 characters. From what I can tell, this happens only when you use the autosummarize feature. We should ensure that the post button is disabled unless the post is 500 words or less.

https://github.com/open-sauced/app/assets/34313413/cc3a105d-5c63-4209-871f-2f8a64c188f4

### Steps to reproduce

1. Create a highlight with this blog post: https://dev.to/opensauced/take-the-first-step-the-open-source-game-15n5 (also, feel free to like that post first 😆)
2. Use the autosummarize feature
3. You should see it go over the limit
4. See the enabled post button 

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by ThePiyushAggarwal** [comment]
I looked into the issue. It also happens when you don't use auto-summarize. It seems that `validCharLimit` function in file `components\molecules\HighlightInput\highlight-input-form.tsx` is validating this.

```ts
  const validCharLimit = () => {
    return charCount - highlightLink.length <= charLimit;
  };
```

| Post Length | - | Link Length | <= | 500 | Result                                                                                            |
|-------------|---|-------------|----|-----|---------------------------------------------------------------------------------------------------|
| 571         | - | 71          | <= | 500 | ![image](https://github.com/open-sauced/app/assets/27003616/ba5b2fd5-0d42-47bc-b672-97d67a4c8422) |
| 572         | - | 71          | <= | 500 | ![image](https://github.com/open-sauced/app/assets/27003616/c313fb44-355f-48c7-9724-000ff02d62ab) |

There must be some reason for the calculation.

**Comment by OgDev-01** [comment]
I think there has been an over-sight here on the algo of the function

The purpose of the function is to validate if the bodyText(content) of the post meets the character limit requirement(which is not more than 500 char).

We have no use case to check if 
```typescript
  charCount - highlightLink.length <= charLimit;
```
it makes no sense here.

The correct check should be
```typescript
   const validCharLimit = () => {
    return charCount <= charLimit;
  };
```
This should be a fix for the issue

**Comment by ThePiyushAggarwal** [comment]
If this is the solution, I would also suggest a small refactor to go.

Instead of a function, we can just convert it into a boolean variable which gets updated automatically whenever there is a change in `charCount` state variable.

```
const hasValidCharCount = charCount <= charLimit;
```

**Comment by OgDev-01** [comment]
Marking this as a good first issue 👍

**Comment by krusecodes** [comment]
.take
