### ISSUE TITLE
Bug: dev card link is undefined for user

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2598]
### Describe the bug

When I click the dev card for geirst, it shows up as undefined. 

At first I thought it was for all unregistered users, but that's not the case.

### Steps to reproduce

1. Go to https://app.opensauced.pizza/user/geirst

![image](https://github.com/open-sauced/app/assets/34313413/64e35567-3836-4a14-800c-7eaef31789f9)

![image](https://github.com/open-sauced/app/assets/34313413/afc82331-dda0-42e4-9baf-c8eac09f48df)

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bobmakesmagics** [comment]
Hi,
I would like to work on this now.

**Comment by bobmakesmagics** [comment]
@BekahHW 
could you assign this to me now?

**Comment by bdougie** [comment]
> @BekahHW could you assign this to me now?

Do you have a solution?

**Comment by aryanas159** [comment]
It is working in the beta deployment.
The undefined is coming because the API returns 404 for this user the main deployment.
![image](https://github.com/open-sauced/app/assets/114330931/2257926e-5e8a-488e-8e81-2c1e66376839)
But the user info is being returned normally in the beta API.
![image](https://github.com/open-sauced/app/assets/114330931/bbe71be2-b222-464e-a09f-3b9463de03c3)

**Comment by Sadaf-A** [comment]
.take

**Comment by brandonroberts** [comment]
This is resolved
