### ISSUE TITLE
Bug: Cannot add contributors to contributor insights

### ISSUE THREAD

**Issue by zeucapua** [open-sauced/app#2754]
### Describe the bug

The `/add-contributors` page for workspace insights errors out.
![image](https://github.com/open-sauced/app/assets/20603494/696e64f9-c8fb-4bea-81b8-9641dccdfa04)

### Steps to reproduce

1. Go to any contributor insights
2. Add a contributor
3. See error modal

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by zeucapua** [comment]
I believe this is because the `addContributorsToList` function
1. only returns an error 
2. POSTs to `/lists/[id]/contrtibutors` endpoint instead of the `/workspaces/[id]/userLists` endpoint since its for workspaces

https://github.com/open-sauced/app/blob/beta/pages/workspaces/%5BworkspaceId%5D/contributor-insights/%5BlistId%5D/add-contributors.tsx#L215

**Comment by jpmcb** [comment]
cc @brandonroberts - I thought this was fixed in: https://github.com/open-sauced/api/pull/565

but looks like the `addListContributor` fetch in the frontend is only sending an array of contributors:

https://github.com/open-sauced/app/blob/8d6f1d1dced63a2d6e9a76e0fde45f36b8a785ca/lib/hooks/useList.ts#L73-L85

where it should be an object of either `id` or `login`

**Comment by brandonroberts** [comment]
@jpmcb Ahh ok, need to adjust this here and when adding a contributor to a list from their profile page
