### ISSUE TITLE
Allow user to choose visibility when creating a new contributor insight

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2863]
- Currently, there's no way to create a new contributor insight page and set it public or private without editing. There should be an option for visibility and an option to upgrade their account on creation.

**Comment by isabensusan** [comment]
Adding the same comment I did on twin issue #2861 

A comment on this:
Since we are moving the public/private controls to the workspace level, we are removing the option to control visibility on the insight page level. This means that if a workspace is public -> then all insights within that workspace are public.

We can revisit more granular visibility controls in the future, but because of the complexity that it entails, we are putting it on hold for the time being.

We could however add in the UI an indicator that the insight page the user is creating is public, because the workspace they are working on is public, and if they want to make it private then they should upgrade. Does that sound like a reasonable solution to this for now?

**Comment by BekahHW** [comment]
@isabensusan do we want to close these 2? Or is there a place we should move these to for a discussion at a later time.
