### ISSUE TITLE
Bug: Workspaces dashboard numbers for opened pull requests is off

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#2872]
### Describe the bug

<img width="1031" alt="image" src="https://github.com/open-sauced/app/assets/42211/3832e84e-e4f4-42e5-9857-414c7b4543a7">

It shows 0 pull requests opened in the last 7 days, but my project shows different.

<img width="1241" alt="image" src="https://github.com/open-sauced/app/assets/42211/78845040-0fc8-4569-ab04-fb8a28eeb865">

May have some impact on API side also

### Steps to reproduce

1. Visit https://app.opensauced.pizza/workspaces/49d4bc7c-d49e-4f98-ab47-12336489f600?range=7
2. Note the 0 opened pull requests

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
These numbers are accurate:

In the last 7 days, 5 PRs were merged and of those 5, all 5 were opened in the last 7 days. The API is assuming that _"opened"_ and _"merged"_ are **_not_** inclusive of each-other. This is partly due to how the pr events occur in the GitHub events feed: there are multiple events that may occur for a PR in a given time period so it takes the "latest" event and populates these stats.

But what I'm hearing is that those stats should maybe be inclusive to eachother? I.e., a merge event should not superced an "open" event in that time range? Is this more accurate to what you'd expect?

```
opened: 5
merged: 5
```

cc @isabensusan for her thoughts here.

**Comment by BekahHW** [comment]
@jpmcb I think this has the potential to be confusing to more users than not. It doesn't seem accurate to say that there were 0 PRs opened in the last 7 days if there were 5 PRs opened. It becomes more confusing when the velocity is 0 days. 

If we don't change the issues open, at the very least, we need a tooltip or something here to explain and we need to update this in the docs/guides.
​
