### ISSUE TITLE
Bug: OG image for workspace not working on X

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2994]
### Describe the bug

When you link to a workspace on X, the OG image doesn't generate.

<img width="512" alt="image" src="https://github.com/open-sauced/app/assets/34313413/bde80432-50e4-49c8-9163-991fa3792e8f">

### Steps to reproduce

You can see it here: 
https://x.com/BekahHW/status/1770222173669433830?s=20

### Browsers

Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
I've looked into this a bit @BekahHW, and I've seen several people reporting this when I search for this on X. Event my own site, nickyt.live, the OG image does not load tand it's the same code, aside from a different image that I have on nickyt.co my main site which does render an OG image.

I wonder if it's just X validating TLDs that aren't standard ones like .com, .co etc. The .pizza and .live aren't standard ones.

Here's some folks talking about it, https://twitter.com/search?q=og%20image%20not%20showing%20twitter&src=typed_query&f=live

And to be clear we have all the correct meta tags for this. I think our other OG images are appearing because they're coming from a known/finally approved source.

**Comment by nickytonline** [comment]
Actually, there is one notable difference. The OG images for workspaces are relative to the root of the site as they are local images, vs. our other OG images which are fully qualified URLs, i.e. starting with `https://...`.

A bit of research suggests that for best compatibility with all social platforms, it's better to have the full URL.

**Comment by nickytonline** [comment]
The code for this can be found at https://github.com/open-sauced/app/blob/beta/components/Workspaces/WorkspaceOgImage.tsx. It uses our SEO component under the hood.

**Comment by jpmcb** [comment]
> When you link to a workspace on X, the OG image doesn't generate.

...

>  I double-checked and the Twitter Card Validator still says the OG image for a workspace is valid. 

Are we certain something isn't broken on X's side? 😅 wouldn't be the first time I've run across a "feature" that's completely broken.

**Comment by nickytonline** [comment]
> > When you link to a workspace on X, the OG image doesn't generate.
> 
> 
> 
> ...
> 
> 
> 
> >  I double-checked and the Twitter Card Validator still says the OG image for a workspace is valid. 
> 
> 
> 
> Are we certain something isn't broken on X's side? 😅 wouldn't be the first time I've run across a "feature" over there that's completely broken.

Yeah, that's what I was thinking originally, but I can't validate that theory as some other OG images render. 😅
