### ISSUE TITLE
Bug: StarSearch input crashes the FrontEnd by returning Status Code 400 reponses

### ISSUE THREAD

**Issue by Idrinth** [open-sauced/app#3472]
### Describe the bug

Using star search to try and get an aggregated lottery factor of an organisation sends the user to an (unreadable) error page. The console output shows multiple 400 responses.

### Steps to reproduce

1. Go to StarSearch
2. Enter 'what repository in the idrinth-api-bench organisation has the highest lottery factor?'
3. Send
4. See the Frontend crash

**Comment by nickytonline** [comment]
Thanks for reporting this @Idrinth! I'm able to reproduce this.

**Comment by nickytonline** [comment]
I was just looking a little closer at the question, `what repository in the `idrinth-api-bench` organisation has the highest lottery factor?` and you're asking about the organization not a specific repository. The bad request is occuring because we're incorrectly assuming the repository you want to get a lotttery factor for is the `idrinth-api-bench` organization and not an actual repository.

Regardless, the frontend shouldn't give the Next.js white screen of death because of that.

**Comment by Idrinth** [comment]
> I was just looking a little closer at the question, `what repository in the `idrinth-api-bench` organisation has the highest lottery factor?`

It was a sensible second step after the proposed question about lottery factor - I did expect it to likely report an error, but not crash the Frontend :)

**Comment by nickytonline** [comment]
It does work sometimes. Regardless, like I said, I'll handle the frontend not exploding. 😅

![CleanShot 2024-05-24 at 08 06 47](https://github.com/open-sauced/app/assets/833231/8c0e8a38-f418-483a-baeb-565dd63c9c97)

**Comment by jpmcb** [comment]
FYI - the API will throw a 400, bad request if our pre-processor agent determines there was some misuse of the system: typically it detects prompt injection attacks. But I'm surprised the client is crashing on 400s since I thought we already handled this on the client side:

<img width="1496" alt="Screenshot 2024-05-24 at 8 25 23 AM" src="https://github.com/open-sauced/app/assets/23109390/c6c61356-44e0-4224-8c39-2274bd8859be">
