### ISSUE TITLE
Feature: clicking on share chat takes a lot of time

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#3615]
### Suggested solution

when clicking on the share chat it takes a bit of time to load the share buttons (mostly cause it creates the chat link in the backend)
it would be great to have a loading state their or something to let the user wait, I think this would not be needed if the threads feature was added since it would just copy the link. 

https://github.com/open-sauced/app/issues/3527

**Comment by jpmcb** [comment]
A loading state would be ideal - it does have to go round trip through to the backend to generate the short link. We have some existing design elements that could help here too!

**Comment by a0m0rajab** [comment]
@jpmcb thanks for the comment

The related code:

https://github.com/open-sauced/app/blob/50c5d1111775d3aafd989fb48478dac304b553a0/components/StarSearch/StarSearchChat.tsx#L623-L666

The loading state should be added at the beginning of the async function and changed when the link is generated. 

This could be a good first issue.

**Comment by ashudevcodes** [comment]
Hey @nickytonline, I am working on this feature to add a loading state to the share chat button. I have implemented the solution, but I'm having an issue. When I click the share button, it fails to fetch the share link and gives a "bad request" or "failed to create a share link" error. However, fetching stream chats or AI-generated chats works fine. I'll attach a video showing the problem and an image of the network fetch error that happens when it tries to fetch the share link. Tell me what I can do to resolve this issue





https://github.com/open-sauced/app/assets/105356967/9ef01d32-98b1-45d7-9438-ad3870c6d10e


![image](https://github.com/open-sauced/app/assets/105356967/0b4d3d13-d952-4334-837a-4f2d75d54e34)
![image](https://github.com/open-sauced/app/assets/105356967/87367be2-c14f-4027-a3f9-9590c0298e90)

**Comment by nickytonline** [comment]
Hi @ashudevcodes. Thanks for your interest in the issue, but it's already assigned to me and i astray have a fix for this.

Feel free to look at other issues that are not assigned to someone.
