### ISSUE TITLE
Feature: YOLO Coders Component

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#3644]
## Context
We have introduced the YOLO Metric in the API to signal users that have been pushing commits directly to the main branch on a project. This component aims to surface this data in the front end, and signal to the user when there's a YOLO coder in a project.

## Mockup ([figma](https://www.figma.com/design/yLXPL9XrTo3pCkQelrGVvy/Repo-Pages?node-id=451-1198&t=bHCzRffsUHNn1Gc3-4))

<img width="1297" alt="image" src="https://github.com/open-sauced/app/assets/27322879/aa94b408-8be8-4b6f-bd86-e96bae6446c1">

<img width="1464" alt="image" src="https://github.com/open-sauced/app/assets/27322879/7cf30439-ec36-4a71-b936-02d96b1b279f">

<img width="600" alt="image" src="https://github.com/open-sauced/app/assets/27322879/1b44ae3f-d6f9-4c82-9a99-ecd8609d2479">

**Comment by jpmcb** [comment]
👏🏼 👏🏼 👏🏼 

This is amazing! Great design!

---

- "maintainer", "external", "member", etc. might be abit difficult to derive from the push data in the API that is surfaced in the yolo coders endpoint. I.e., that metadata doesn't go along with those pushes. We could probably look in the prs, pr reviews, or issue comments to determine that.
  - On that note, adding this data to the lottery factor wouldn't be too bad since that data goes alongside the pull requests in the "pr_author_association" column
- Should be able to construct the GitHub sha link as `https://github.com/{org}/{name}/commit/{head_sha}` and that'd take you right to the head commit push. It's tricky to try to show the full range of multiple commits that get pushed at once. But in theory, you should be able to see what was pushed from the last `HEAD` - we'll have to play around with this to validate

**Comment by jpmcb** [comment]
Supersede https://github.com/open-sauced/app/issues/3584 (although, still relevant context there on how the API endpoint works)
