### ISSUE TITLE
Bug: TypeError: Cannot read properties of undefined (reading 'split') after signing up to OpenSauced

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3649]
A user reported after signup a client-side crash.

![image](https://github.com/open-sauced/app/assets/833231/77bedb7f-a165-4324-807d-ebf2f251c3cc)

It looks like a string is undefined somewhere. Looking at our codebase, it could be either trying to split a GitHub user's interests or it's a repo that is `undefined` trying to be split on `/`. I'm leaning more towards the GitHub interests being the issue without knowing exactly where this happened, but it is post signup.

**Comment by jpmcb** [comment]
Mentioning this here as well:

---

Interests can definitely be `EMPTY` in the database which should get surfaced in the `v2/users/{username}` endpoint as `"interests": ""`. So, this shouldn't be undefined.

Two questions:
- Can we replicate this reliably with new test users?
- Surprised this wasn't caught by Sentry since it throws in the client. Worth investigating why that might have been.

**Comment by nickytonline** [comment]
As @jpmcb mentioned, odd that this wasn't caught by Sentry. We'lll need to see if this can be reproduced.
