### ISSUE TITLE
time-range filter should persist when selecting different dashboard in repo pages

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#3657]
When I'm on the Overview dashboard for repo pages and change the range, I expect that range to persist when I click the contributors tab. Instead, it goes back to the default of 30days.

## Replicate
1. Go here: https://app.opensauced.pizza/s/statelyai/xstate?range=90
2. Now select the contributors tab
3. See that it resets to 30d

https://github.com/open-sauced/app/assets/34313413/d55f2e71-4e48-4c19-bffd-de63bca3a3dd

**Comment by ashudevcodes** [comment]
.take

**Comment by nickytonline** [comment]
@ashudevcodes, I'm assigning this to you, but next time ensure you're assigned to avoid doing a bunch of work in a pull request. Issues get the needs triage label because the team still needs to see what needs to be done or if it's ready to be worked on.

![CleanShot 2024-07-02 at 10 04 52](https://github.com/open-sauced/app/assets/833231/32f05e2c-d5a7-499f-9103-30c5496b3864)
