### ISSUE TITLE
Bug: Error on SBOM import

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#3873]
### Describe the bug

When building an SBOM for nasa/open. Because I am importing for an SBOM, there 70+ repos and no indication of what is failing. 

![Screenshot 2024-08-06 at 12 50 43 PM](https://github.com/user-attachments/assets/5019f52f-60cf-4929-8a14-ea5270bc80b6)

Failed on "eslint-plugin-no-unsanitized/issues"

### Steps to reproduce

1. Add a repository insight
2. Import SBOM using "nasa/openmct"
3. Hit create and confirm the error. 

My suggestion is skipping the repos that error and let the user know it was skipped, but allow the insight to be created. 

The insight does get created despite the error, and filled with unrelated repos. Note the three instances of them while I was trying to triage. 

![Screenshot 2024-08-06 at 12 51 38 PM](https://github.com/user-attachments/assets/88642c09-838d-4be3-8e15-6346b1dec119)

**Comment by bdougie** [comment]
I can't delete an insight without upgrading as well. This is a dark pattern, that we will need to update as well.

![Screenshot 2024-08-06 at 12 53 38 PM](https://github.com/user-attachments/assets/6f512829-7699-436c-8cde-fccaf702b5d6)

**Comment by zeucapua** [comment]
re: @bdougie 

When clicking the upgrade from the modal, it takes you to the workspace settings since it has the option, not the repository insight settings. The fact that the insight settings are gated behind an upgrade is confusing via the UI. You can get around this by changing the URL directly from `.../dashboard` to `.../edit` to get to the settings.

- Should I make an issue to only block the 'Update Workspace' button on the insight's settings rather than gating the page altogether?

- Are there options below that aren't allowed for non-upgraded users if the insight/workspace is above the limit? Eg. Users shouldn't be able to edit the repositories on creation if over the limit? 

![image](https://github.com/user-attachments/assets/84916efb-6927-40f8-aa23-7c03034f39b2)

**Comment by brandonroberts** [comment]
I'll get a fix in on the API side for the repository import. The repository URL for the one that caused the failure is https://github.com/mozilla/eslint-plugin-no-unsanitized/issues

**Comment by brandonroberts** [comment]
@zeucapua Yea, they should be able to edit the repository insight if only to be able to delete it even if they are over the overall repository limit.

**Comment by brandonroberts** [comment]
Fixed parsing of the repository full names in the API for SBOM generation
