### ISSUE TITLE
Bug: Dev Card with long username cause OSCR to pop out of card

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3981]
A dev card with long username causes the OSCR score to pop out of card. You can see an example of this on Josh's dev card page. https://app.opensauced.pizza/u/JoshuaKGoldberg/card

![CleanShot 2024-08-18 at 13 34 15](https://github.com/user-attachments/assets/91f0467d-56bd-42f1-a10d-b34c3d5cd1ca)

Note that the OG image is fine, as we don't add the OSCR score beside the username.

**Comment by Mandeep56Singh** [comment]
.take

**Comment by BekahHW** [comment]
@Mandeep56Singh I assigned you if you're still up for it!

**Comment by Mandeep56Singh** [comment]
@nickytonline I had some hydration error while solving this issue which I have fixed in this pr. 
Sorry for mixing two separate things together. 
I am not sure exactly which part was responsible for it, but addressing props.devstats.isLoading has fixed the hydration error.
I had no chrome extension which was effecting hydration.
kindly review it.
This is the screenshot of hydartion error I had 
![Screenshot (424)](https://github.com/user-attachments/assets/839e906c-577b-4cb1-b720-b59dc021b0b2)
