### ISSUE TITLE
Bug: workspace selection dropdown shows duplicate default workspace and has duplicate hover state

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/app#3984]
### Describe the bug

Attached is a screen record of the bug
https://github.com/user-attachments/assets/dc584b47-4f0e-430d-8def-6cf3332d911d

### Steps to reproduce

1. Goto workspace root page
2. click to open the sidenav
3. Select the dropdown to create/select workspaces
4. you'll see the default workspace is duplicated

**Comment by jpmcb** [comment]
Good to see you Sunday!! Thanks for reporting this: we did recently see this happen where people's default workspaces were re-created due to some weird auth flows in the API (i.e., someone wasn't found in the database so it attempted to re-create them and their resources).

Cc @brandonroberts did you investigate this originally?

**Comment by brandonroberts** [comment]
Yep. I think it came down to the API being under load at the time when this happens. We can add some checks in the API to make sure another default workspace isn't created. You can delete the second one without issue.

**Comment by OgDev-01** [comment]
Alright.. Thanks for the clarifications. I'll delete the duplicate right away.

Is it ok if i close this issue? or do we leave it open for tracking purposes? cc: @brandonroberts

**Comment by brandonroberts** [comment]
Thanks @OgDev-01. You can close it. We are tracking this internally also
