### ISSUE TITLE
Feature: downtime page

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#4156]
### Suggested solution

We need a 1 off downtime page on a separate branch that we can deploy to Netlify in the case we have some scheduled downtime.

This should be _very_ simple but still stylistic enough to be on brand (cc @isabensusan).

This should be cut to a separate branch called `downtime` that we can deploy from and kept as a sovereign branch that we use in the case we schedule some downtime.

**Comment by nickytonline** [comment]
As suggested on Slack, for design, we could keep a simple static page like the login success of the pizza CLI maybe? Just HTML and CSS. https://github.com/open-sauced/pizza-cli/blob/beta/api/auth/success.html

I'll put up a draft PR with this and feel free to slice and dice. We can deploy it via the Netlify CLI so that we don't have to modify settings in Netlify and disrupt our site configuration.

**Comment by brandonroberts** [comment]
Closed by https://github.com/open-sauced/app/pull/4157
