### ISSUE TITLE
Refractor: Rename the [filterName] query to more accurate naming in /pages routes

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/app#849]
### Type of feature

🧑‍💻 Refactor

### Current behavior

In `/pages` path inside pages directory, there is [filterName] query that is actually the page's id. This name is inaccurate and can cause a lot of confusion.

![image](https://user-images.githubusercontent.com/52013393/217756535-353acc12-6408-4f84-b545-92b88f2f23bf.png)

### Suggested solution

Renaming it to [pageId] for example.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by babblebey** [comment]
I concur to this, I got pretty confused as I was finding my way around the codebase.

**Comment by babblebey** [comment]
I concur to this, I got pretty confused as I was finding my way around the codebase.

**Comment by nickytonline** [comment]
.take

**Comment by 5hraddha** [comment]
.take

**Comment by 5hraddha** [comment]
Hi @Deadreyo,
After looking into the issue, what I found is that, its not just changing the dynamic query param name from `[filterName]` to `[pageId]` in `/pages` path inside `pages` directory, it will involve few other updates such as:
1.  renaming the params name from `[filterName]` to `[pageId]` in `getServerSideProps` in `[toolName].tsx` and `[...selectedFilter].tsx`.
2. updating `filterName` to `pageId` in Hub Page Layout - `layouts/hub-page.tsx` and `useInsights.ts` hook as they are dependent on the parsed query strings. And since `useInsight` hook itself is being used by other components, we might have to test to make sure none of them are breaking.

Before going ahead with the change, I wanted to check with you guys, if it is fine to go ahead with the dynamic query param name change?

**Comment by babblebey** [comment]
Hi @5hraddha 

Great to have you here!

Please go on and make every necessary change within the context of your fix/refactor that you deem fit to cook your Pull Request 😉

It's your slice 🍕, we can't wait to see it fit into the pizza box 🤓

**Comment by brandonroberts** [comment]
Thanks @5hraddha. @nickytonline took this one already, so please check with them before making more changes. This is quite a large refactor even though its presented as a relatively small change, as we're using that route param in multiple places across the application.

**Comment by 5hraddha** [comment]
Hi @nickytonline,
What's your take on this? I'm fine to do the changes and test but feel, its better that the team decide on it. I'll proceed accordingly. Thanks!

**Comment by nickytonline** [comment]
To your point though, it's not just changing the file name, so make the changes elsewhere as well as you had proposed.

**Comment by brandonroberts** [comment]
Ok cool, as you were 😄. Thanks Nick!

**Comment by 5hraddha** [comment]
Great! 😅 Thanks Nick and Brandon! I'll proceed with the changes then.
